name: Build Mod (iOS)

on:
  push:
    branches: ['**']
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Build the mod
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          build-config: 'Release'
          target: iOS
          combine: true
          # sdk: 'nightly'   # décommente si le SDK est trop ancien

      - name: Upload the built .geode
        uses: actions/upload-artifact@v4
        with:
          name: SafeNoclip-iOS
          path: ${{ steps.build.outputs.build-output }}
